/**
 * OpenAPI Notastore
 * This is a sample server Notastore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiNotastore);
  }
}(this, function(expect, OpenApiNotastore) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiNotastore.NotaApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotaApi', function() {
    describe('addNota', function() {
      it('should call addNota successfully', function(done) {
        //uncomment below and update the code to test addNota
        //instance.addNota(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNota', function() {
      it('should call deleteNota successfully', function(done) {
        //uncomment below and update the code to test deleteNota
        //instance.deleteNota(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findNotasByStatus', function() {
      it('should call findNotasByStatus successfully', function(done) {
        //uncomment below and update the code to test findNotasByStatus
        //instance.findNotasByStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findNotasByTags', function() {
      it('should call findNotasByTags successfully', function(done) {
        //uncomment below and update the code to test findNotasByTags
        //instance.findNotasByTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotaById', function() {
      it('should call getNotaById successfully', function(done) {
        //uncomment below and update the code to test getNotaById
        //instance.getNotaById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNota', function() {
      it('should call updateNota successfully', function(done) {
        //uncomment below and update the code to test updateNota
        //instance.updateNota(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNotaWithForm', function() {
      it('should call updateNotaWithForm successfully', function(done) {
        //uncomment below and update the code to test updateNotaWithForm
        //instance.updateNotaWithForm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadFile', function() {
      it('should call uploadFile successfully', function(done) {
        //uncomment below and update the code to test uploadFile
        //instance.uploadFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
